import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

import fs from 'fs';

const getDocsFromDir = (dir: string) => 
  fs.existsSync(`./docs/MEDS-DEV/${dir}`)
    ? fs.readdirSync(`./docs/MEDS-DEV/${dir}`)
        .filter(file => file.endsWith('.md'))
        .map(file => `MEDS-DEV/${dir}/${file.replace('.md', '')}`)
    : [];

const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  medsDevSidebar: [
    {
      type: 'category',
      label: 'MEDS-DEV Structure',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Datasets',
          items: getDocsFromDir('Datasets'),
        },
        {
          type: 'category',
          label: 'Models',
          items: getDocsFromDir('Models'),
        },
        {
          type: 'category',
          label: 'Tasks',
          items: getDocsFromDir('Tasks'),
        },
      ],
    },
  ],
};

export default sidebars;
